name: demo
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello!"
          echo `date`
          echo "secrect TEST: ${TEST} =="
          echo "Bye!"
          echo `ls -la`
          echo `pwd`
        env:
          TEST: ${{ secrets.TEST }}
