name: demo
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello!"
          echo `date`
          echo "secrect TEST: ${TEST} (len: ${#TEST})=="
          echo "Bye!"
          echo `ls -la`
          echo `pwd`
          echo `which python`
          echo `which python3`
        env:
          TEST: ${{ secrets.TEST }}
