name: demo
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello!"
          echo `date`
          echo $TEST
          echo "Bye!"
        env:
          TEST: ${{ secrets.TEST }}
